name: run on prerelease

on: 
  release:
    types: [prereleased]

permissions:
  id-token: write # This is required for requesting the AWS JWT
  contents: read  # This is required for actions/checkout

jobs:
  plan_prod:
    runs-on: ubuntu-20.04
    env:
      TF_VERSION: "1.2.8"
      TF_AGENT_POOL_ID: "apool-3BXHFcvMX5e3gvMT"
      NODE_VERSION: 20.12.x

    steps:
      - uses: actions/checkout@v3
      - run: echo "started from prerelease"
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
